// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code エラーコード。
	Code int `json:"code"`

	// Message エラーメッセージ。
	Message string `json:"message"`
}

// JwtError defines model for JwtError.
type JwtError struct {
	// Message ユーザ向けのメッセージ。
	Message string `json:"message"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Detail 特定の発生事象に関する詳細な説明。
	Detail *string `json:"detail,omitempty"`

	// Instance エラーが発生したリソースのURI。
	Instance *string `json:"instance,omitempty"`

	// RequestId デバッグ用のリクエストID。
	RequestId *string `json:"request_id,omitempty"`

	// Status 発生したHTTPステータスコード。
	Status int32 `json:"status"`

	// Title エラーの短い要約。
	Title string `json:"title"`

	// Type エラータイプを識別するURI。
	Type string `json:"type"`
}

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	// Title タスクのタイトル。
	Title string `json:"title"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CreatedAt タスクの登録日時。
	CreatedAt string `json:"created_at"`

	// Id タスクのID。
	Id uint64 `json:"id"`

	// Title タスクのタイトル。
	Title string `json:"title"`

	// UpdatedAt タスクの更新日時。
	UpdatedAt string `json:"updated_at"`
}

// UserRequest ユーザーアカウント情報。
type UserRequest struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Password ユーザーの平文のパスワード。
	Password string `json:"password"`
}

// UserResponse ユーザーアカウント情報。
type UserResponse struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Id ユーザーの固有識別子。
	Id uint64 `json:"id"`
}

// JWT defines model for JWTトークンエラー.
type JWT = JwtError

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XCSRFTOKEN CSRFトークン。
	XCSRFTOKEN *string `json:"X-CSRF-TOKEN,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = UserRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = TaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context, params LoginParams) error
	// ログアウト
	// (POST /logout)
	Logout(ctx echo.Context) error
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx echo.Context) error
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx echo.Context) error
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx echo.Context) error
	// タスクの削除
	// (DELETE /tasks/{taskID})
	DeleteTask(ctx echo.Context, taskID uint64) error
	// タスクの取得
	// (GET /tasks/{taskID})
	GetTaskByID(ctx echo.Context, taskID uint64) error
	// タスクの更新
	// (PUT /tasks/{taskID})
	UpdateTask(ctx echo.Context, taskID uint64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Csrf converts echo context to params.
func (w *ServerInterfaceWrapper) Csrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Csrf(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-TOKEN")]; found {
		var XCSRFTOKEN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-TOKEN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-TOKEN", valueList[0], &XCSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-TOKEN: %s", err))
		}

		params.XCSRFTOKEN = &XCSRFTOKEN
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx, params)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// GetAllTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllTasks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllTasks(ctx)
	return err
}

// CreateTask converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTask(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTask(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskID" -------------
	var taskID uint64

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", ctx.Param("taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, taskID)
	return err
}

// GetTaskByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetTaskByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskID" -------------
	var taskID uint64

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", ctx.Param("taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTaskByID(ctx, taskID)
	return err
}

// UpdateTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskID" -------------
	var taskID uint64

	err = runtime.BindStyledParameterWithOptions("simple", "taskID", ctx.Param("taskID"), &taskID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTask(ctx, taskID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.Csrf)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.POST(baseURL+"/signup", wrapper.SignUp)
	router.GET(baseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(baseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(baseURL+"/tasks/:taskID", wrapper.DeleteTask)
	router.GET(baseURL+"/tasks/:taskID", wrapper.GetTaskByID)
	router.PUT(baseURL+"/tasks/:taskID", wrapper.UpdateTask)

}

type JWTJSONResponse JwtError

type CsrfRequestObject struct {
}

type CsrfResponseObject interface {
	VisitCsrfResponse(w http.ResponseWriter) error
}

type Csrf200JSONResponse struct {
	// CsrfToken CSRFトークン。
	CsrfToken string `json:"csrf_token"`
}

func (response Csrf200JSONResponse) VisitCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200Response struct {
	Headers Login200ResponseHeaders
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type Login400JSONResponse string

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login500ApplicationProblemPlusJSONResponse ProblemDetails

func (response Login500ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200ResponseHeaders struct {
	SetCookie string
}

type Logout200Response struct {
	Headers Logout200ResponseHeaders
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201JSONResponse UserResponse

func (response SignUp201JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SignUp409ApplicationProblemPlusJSONResponse ProblemDetails

func (response SignUp409ApplicationProblemPlusJSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SignUp500ApplicationProblemPlusJSONResponse ProblemDetails

func (response SignUp500ApplicationProblemPlusJSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasksRequestObject struct {
}

type GetAllTasksResponseObject interface {
	VisitGetAllTasksResponse(w http.ResponseWriter) error
}

type GetAllTasks200JSONResponse []TaskResponse

func (response GetAllTasks200JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks401JSONResponse struct{ JWTJSONResponse }

func (response GetAllTasks401JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks500ApplicationProblemPlusJSONResponse ProblemDetails

func (response GetAllTasks500ApplicationProblemPlusJSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse TaskResponse

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask400JSONResponse map[string]interface{}

func (response CreateTask400JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask401JSONResponse struct{ JWTJSONResponse }

func (response CreateTask401JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask500ApplicationProblemPlusJSONResponse ProblemDetails

func (response CreateTask500ApplicationProblemPlusJSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	TaskID uint64 `json:"taskID"`
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTask401JSONResponse struct{ JWTJSONResponse }

func (response DeleteTask401JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask500ApplicationProblemPlusJSONResponse ProblemDetails

func (response DeleteTask500ApplicationProblemPlusJSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByIDRequestObject struct {
	TaskID uint64 `json:"taskID"`
}

type GetTaskByIDResponseObject interface {
	VisitGetTaskByIDResponse(w http.ResponseWriter) error
}

type GetTaskByID200JSONResponse TaskResponse

func (response GetTaskByID200JSONResponse) VisitGetTaskByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByID500ApplicationProblemPlusJSONResponse ProblemDetails

func (response GetTaskByID500ApplicationProblemPlusJSONResponse) VisitGetTaskByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	TaskID uint64 `json:"taskID"`
	Body   *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse TaskResponse

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask500ApplicationProblemPlusJSONResponse ProblemDetails

func (response UpdateTask500ApplicationProblemPlusJSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx context.Context, request CsrfRequestObject) (CsrfResponseObject, error)
	// ログイン
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウト
	// (POST /logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx context.Context, request GetAllTasksRequestObject) (GetAllTasksResponseObject, error)
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// タスクの削除
	// (DELETE /tasks/{taskID})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)
	// タスクの取得
	// (GET /tasks/{taskID})
	GetTaskByID(ctx context.Context, request GetTaskByIDRequestObject) (GetTaskByIDResponseObject, error)
	// タスクの更新
	// (PUT /tasks/{taskID})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Csrf operation middleware
func (sh *strictHandler) Csrf(ctx echo.Context) error {
	var request CsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Csrf(ctx.Request().Context(), request.(CsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Csrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CsrfResponseObject); ok {
		return validResponse.VisitCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context, params LoginParams) error {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllTasks operation middleware
func (sh *strictHandler) GetAllTasks(ctx echo.Context) error {
	var request GetAllTasksRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTasks(ctx.Request().Context(), request.(GetAllTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllTasksResponseObject); ok {
		return validResponse.VisitGetAllTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(ctx echo.Context) error {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx.Request().Context(), request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		return validResponse.VisitCreateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(ctx echo.Context, taskID uint64) error {
	var request DeleteTaskRequestObject

	request.TaskID = taskID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx.Request().Context(), request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		return validResponse.VisitDeleteTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTaskByID operation middleware
func (sh *strictHandler) GetTaskByID(ctx echo.Context, taskID uint64) error {
	var request GetTaskByIDRequestObject

	request.TaskID = taskID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskByID(ctx.Request().Context(), request.(GetTaskByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTaskByIDResponseObject); ok {
		return validResponse.VisitGetTaskByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(ctx echo.Context, taskID uint64) error {
	var request UpdateTaskRequestObject

	request.TaskID = taskID

	var body UpdateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx.Request().Context(), request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		return validResponse.VisitUpdateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa/XPTRvr/VzT7/f5WJ7Yc5yBimDlC4Gp6Q1OSXK/DZBjF2jgCWxK76xKX8QyS2hJI",
	"rg05mpCDmZQMDSFpnPTC9Mpb+WMWO+a/uNldv0i25Beapu3xQyz08uzz8vk8+3lkXwcpM2uZBjQIBsp1",
	"gCC2TAND/p9zH49Td466L6mzS9196mxS9wl1X7JrKdMg0CDsULWsjJ5SiW4a0cvYNNg5OKtmrUxnMziX",
	"zaooD5TwuyLgUzWTg+zuLMRYTUOggKyOsW6kJRNJWTUzbaIs1KTL1wgoFAoRgFMzMKuyJ/4fwWmggP+L",
	"NsKMiqs4eu4aOYOQicQzGsQppFssCuFNZesflc2X1C7WXaE3HNAwz2PjBi5Uk8ZOWMi0ICK6CD1lavys",
	"33jDoLPP/rq3mOUIIHmLxaYbBKYhAoVII+BwE+5D6rrUecHN/eQzhAnSjTR3GcGrOR1BDSgXhVMN25P1",
	"+82pyzBF2Lr11LREFO6Ru8Fd+LG0eIfad1jeenetnU+jyJzKwOwIJKqewa2eafxCq2MHt56Viv+idvFg",
	"9fnB3bU3z+crPzyk9vbb5XVqr1JnvvJk/+DpHrW3Klvfl+99JfysAhgooLxwkz//DXUWqL2WHKHOUnnB",
	"pvYj6qxT5xF1v6Tut9TeLe3cKz3YpPYKtX+m9n3q/DMw5AjQDUxUI9W2rPaCcJebW6PuFnVe8Tw+o3Zx",
	"4kKy2ctoDkOEo3J8IDEIIoAxQiVAATmkB7nAkg4xuaRrQZW8Sd1FXrq9g7ubvJJbjJXOJlvenUuONK+O",
	"4NW+2fxnfXJ8IGg1TFSSwwGl8YT4/vj4KDf/JQ/zNTv206O+XCKW8ESoG2QgHsgeopNM+yQXD9Z2qP15",
	"ZcM+ePp5c1D+pC9UNuZZze156tyuVzgoWnGiDelfc9SsUGepsnOvNPedgGFAUWcIsbASjVbP9KfMbNRC",
	"5hSOGibpmzZzhtax1k0M41drqalXJohv4yq+ckHApJVsoakVddvlbVPEOUfd7W64L0yGexLaYxFUCdQu",
	"qaS9PwerL94u/Lu88l151QkjptbeRA34jYzrBvlTojfw9ZChCMhZWlfBle8/LS/vtQmuKdm65gGBJ4O+",
	"FYNqMYEh8qAiZA/gf9eps02dDbaZu3Nl94vStz8I1/z1g9nAtu2zVd1MXrJEOeusI7jfs9iDk2apGF8z",
	"kdbRaOnZfnn5Jrd+h/ee3YDtOCSDwm3PYuHZaiD3d5kuvYtE3X9efnBLdKvSzmK3LAgCnfC/NVkFvjFO",
	"mzVxqaYYwFqE2bipmTymFdae7SLbHB2b2sVTo0lqP2atVEQp6Mfvl06NJpmMhAgLI3J/jAVuWtBQLR0o",
	"YKA/1i/zYpIZnuVoCqNpdpCGATg/PXbhrF+sLh3cXSvPLYpOLjxgReOiOKmxR5i9iF9fx2Ox7qU0vxOj",
	"6UvEvAKZE7Nnkx9Na8nhs8PpTz7Aw+emz+c+/tvER5+c0pPnL189kwE+IdzUMz2GOgbXjaRs2AuurH8J",
	"oaJhKod0kgfKxcmIZxBoWZ8rt8rDBeaFmsZsPSZ2wCSzEs2YaZ1HYZntWxIjxQ519njLZSUrFdfKy6/C",
	"S/ZXbpmBAqlZSCBiS3eXrcYWDhiq2VYOVQ0iEAGGmmXn/97Hnuwb//CDM+eBt1DNiZ6si7VhU8v3hpdq",
	"r+Dpkv9MICZMQniblgLYWSbbuh6bvDtAwQ8EgnKwEAzyJgBEqgnht4xB0nfaNK/ogfvlC65E/0Pdx9Td",
	"5+q7tLhNnRtMMEriMereYze5N6pDmrcAHJUn1amUHB+YzX927PjQCWlUJTMnoyek9wmxPjQy+RPSGAMj",
	"PCGNqVk4phN4cowgPUXaVobFnuiKwm1stFIjAgbbGrXEHPReUH/g4+ZgLOaZHEEK5S1iRqf4pyLNqHgG",
	"aqNVAEg6lgyTSGQG8iuSOc2P0/qn0JDqMOkaHE1DWq/c9zI0lO5mjnTDd2epZm2db6tzbZnOjB42cnc5",
	"cneq49yT59TepvYWdeY7wKqLBFVDCs4R1tNGzuoiR0ISd9EKx/S0MWGBP3wrkg/JaSaZZJ/vs41/vfpf",
	"lYcBXDkthDngjWboEHsCRMhEEtf9upGWWHyK1BTloXL+sJtaLfNKvUexTlYrf/8RNiwflYL5SFR8BYeK",
	"Se8Y9+anG5WNx4yQXy+Xfl4JJ+RfIDmVyYxzw79MVV70T9AgHosP9snxvtixcXlIkYeUxGB/bGBQjsnv",
	"xYaUWKyB/prEZuHJ/smxCzOFSMeFj/UfPzYgDyV8C8f9C8c7L9xkhimqBjZ0ArO4E0h8LyDqb3iAipCa",
	"D8N7QjSbILP1ckVDX3r3TJijQXsNqlWc2kWBUw/sWU3AJBvCg7eeOtidpfLyXmXj6zevHrQfnDhGWAV+",
	"yfZTHwc5VrvuDt53YL/GBhNGgHhciQ0qg4n+wVjieGLIT72BiC+cgTYMCLHTY/zhGxR4dwncbjr8H2cP",
	"tYte7Leyp75pRK+zj+RIQTApA0mA0Gz9gqL6arHKs9Kt229XH4UzbITbrTKs7bAb9C60jma5OulaKplp",
	"zLnCf9DMHC8Au3iPNNlCtESAND963DTGTAFnSTOhGKjgrI794+MRIUtUO6gjB6qPTuCpvL5bf6fWIkEY",
	"ZobzvLx/FNzEDqdB/7oK5TDb87sCGsEUU9UMy7Uvmo4ey+HqIvcOWBZfkoQ3wglepd9/I3wHDcTRL/t/",
	"cVFevlnaWSl/s1f58Yu39lfeH1rU8CsyolVVUyEC4k0m5hZLt9faPCn38oOMntVWb8Ljt2IST4kiZfSs",
	"TqAmZdVZSY5JqRkV9f8WpBIsCBAdhfqp6zXQ8iGWTWoeEIPCZOG/AQAA//88C58sNyQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
