// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	// Message ユーザ向けのメッセージ。
	Message string `json:"message"`
}

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	// Title タスクのタイトル。
	Title string `json:"title"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CreatedAt タスクの登録日時。
	CreatedAt string `json:"created_at"`

	// Id タスクのID。
	Id uint64 `json:"id"`

	// Title タスクのタイトル。
	Title string `json:"title"`

	// UpdatedAt タスクの更新日時。
	UpdatedAt string `json:"updated_at"`
}

// UserRequest ユーザーアカウント情報。
type UserRequest struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Password ユーザーの平文のパスワード。
	Password string `json:"password"`
}

// UserResponse ユーザーアカウント情報。
type UserResponse struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Id ユーザーの固有識別子。
	Id uint64 `json:"id"`
}

// JWT defines model for JWTトークンエラー.
type JWT = ApiResponse

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XCSRFTOKEN CSRFトークン。
	XCSRFTOKEN *string `json:"X-CSRF-TOKEN,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = UserRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = TaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context, params LoginParams) error
	// ログアウト
	// (POST /logout)
	Logout(ctx echo.Context) error
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx echo.Context) error
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx echo.Context) error
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx echo.Context) error
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx echo.Context, taskId int) error
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx echo.Context, taskId int) error
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx echo.Context, taskId int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Csrf converts echo context to params.
func (w *ServerInterfaceWrapper) Csrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Csrf(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-TOKEN")]; found {
		var XCSRFTOKEN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-TOKEN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-TOKEN", valueList[0], &XCSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-TOKEN: %s", err))
		}

		params.XCSRFTOKEN = &XCSRFTOKEN
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx, params)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// GetAllTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllTasks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllTasks(ctx)
	return err
}

// CreateTask converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTask(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTask(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, taskId)
	return err
}

// GetTaskById converts echo context to params.
func (w *ServerInterfaceWrapper) GetTaskById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTaskById(ctx, taskId)
	return err
}

// UpdateTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTask(ctx, taskId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.Csrf)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.POST(baseURL+"/signup", wrapper.SignUp)
	router.GET(baseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(baseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(baseURL+"/tasks/:taskId", wrapper.DeleteTask)
	router.GET(baseURL+"/tasks/:taskId", wrapper.GetTaskById)
	router.PUT(baseURL+"/tasks/:taskId", wrapper.UpdateTask)

}

type JWTJSONResponse ApiResponse

type CsrfRequestObject struct {
}

type CsrfResponseObject interface {
	VisitCsrfResponse(w http.ResponseWriter) error
}

type Csrf200JSONResponse struct {
	// CsrfToken CSRFトークン。
	CsrfToken string `json:"csrf_token"`
}

func (response Csrf200JSONResponse) VisitCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200Response struct {
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Login400JSONResponse string

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse string

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201JSONResponse UserResponse

func (response SignUp201JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SignUp400JSONResponse string

func (response SignUp400JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SignUp500JSONResponse string

func (response SignUp500JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasksRequestObject struct {
}

type GetAllTasksResponseObject interface {
	VisitGetAllTasksResponse(w http.ResponseWriter) error
}

type GetAllTasks200JSONResponse []TaskResponse

func (response GetAllTasks200JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks401JSONResponse struct{ JWTJSONResponse }

func (response GetAllTasks401JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks500JSONResponse string

func (response GetAllTasks500JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse TaskResponse

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask400JSONResponse map[string]interface{}

func (response CreateTask400JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask401JSONResponse struct{ JWTJSONResponse }

func (response CreateTask401JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask500JSONResponse map[string]interface{}

func (response CreateTask500JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	TaskId int `json:"taskId"`
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTask401JSONResponse struct{ JWTJSONResponse }

func (response DeleteTask401JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask500JSONResponse string

func (response DeleteTask500JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByIdRequestObject struct {
	TaskId int `json:"taskId"`
}

type GetTaskByIdResponseObject interface {
	VisitGetTaskByIdResponse(w http.ResponseWriter) error
}

type GetTaskById200JSONResponse TaskResponse

func (response GetTaskById200JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskById500JSONResponse string

func (response GetTaskById500JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	TaskId int `json:"taskId"`
	Body   *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse TaskResponse

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask500JSONResponse string

func (response UpdateTask500JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx context.Context, request CsrfRequestObject) (CsrfResponseObject, error)
	// ログイン
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウト
	// (POST /logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx context.Context, request GetAllTasksRequestObject) (GetAllTasksResponseObject, error)
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx context.Context, request GetTaskByIdRequestObject) (GetTaskByIdResponseObject, error)
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Csrf operation middleware
func (sh *strictHandler) Csrf(ctx echo.Context) error {
	var request CsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Csrf(ctx.Request().Context(), request.(CsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Csrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CsrfResponseObject); ok {
		return validResponse.VisitCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context, params LoginParams) error {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllTasks operation middleware
func (sh *strictHandler) GetAllTasks(ctx echo.Context) error {
	var request GetAllTasksRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTasks(ctx.Request().Context(), request.(GetAllTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllTasksResponseObject); ok {
		return validResponse.VisitGetAllTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(ctx echo.Context) error {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx.Request().Context(), request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		return validResponse.VisitCreateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(ctx echo.Context, taskId int) error {
	var request DeleteTaskRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx.Request().Context(), request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		return validResponse.VisitDeleteTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTaskById operation middleware
func (sh *strictHandler) GetTaskById(ctx echo.Context, taskId int) error {
	var request GetTaskByIdRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskById(ctx.Request().Context(), request.(GetTaskByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTaskByIdResponseObject); ok {
		return validResponse.VisitGetTaskByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(ctx echo.Context, taskId int) error {
	var request UpdateTaskRequestObject

	request.TaskId = taskId

	var body UpdateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx.Request().Context(), request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		return validResponse.VisitUpdateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZa2/TVh//KtZ5nnePm8Rp+kD9ai2XKTBxbccQqpCJT1KX+MI5J9CqikQcIVrWjYKg",
	"XQdSB4LCYC3dmBCXMj6MSQjfYvof52InduKUljFekNSx/9ff7385nkUZU7dMAxuMInkWEUwt06CY/3Ho",
	"1JhTnnPKW479zCk/d+zHTvlXp7wFv2VMg2GDwVfFsvJaRmGaacSnqGnANTyt6Fa+txha0HWFzCA5/C4R",
	"XVTyBQx365hSJYeRjHSNUs3ICSYRdCWfNYmOVWHqEkPFYlFENDOJdQWe+C/BWSSj/8RbbsbdX2l8xNJO",
	"1N11H1MxzRDNAkdcg2pPfqg93nJKG01rnMs2amng7nnFyLPIIqaFCdNc35sWz7ZJd8pr3NcXlcUbTukG",
	"6Cjfc8plx37Dr78ETSJiMxa4SxnRjBzXTPCFgkawiuQzTekTzRvNc1M4w1BRRGMKPX8CXyhgyjrNYhrL",
	"Bxllv3PsV5AAcPmdYz/gKXkaxRZXZLglYRHKEKwwrJ5VWHd7Pqy8+bjwR3X5YXXFDrRHRJraXUR6v/sg",
	"wAXUoYJmsP+nWqI0g+EcJiBrJyIkooKlRnKueufP6tJmF+fagq2pqGGi6I2gT2NQLsYpJh5UhGCS/3/f",
	"sZ869hpwsTxXLV+p/PK7a5o/f1hXtHwPWXVwb0Gg7PtOed4p/wa+BwfNUii9ZBK1p9DKq+fVpatc+g0Q",
	"V37GdcxHiaBrtkdZeLRayP0iw6VFCNSd19W787X1nypzDyvri1FZEAQ61/7OYMHNmpE1G71ByQDAOorq",
	"mKma3Kdlp/wEHC2tOnbJKW2MHEs7pUdOaaXupUs/fr8wciwNXQAT6gqRYglw3LSwoVgaktFgLBGTeDLZ",
	"JI9yPENJFr7kcADO9508cdDfa25+uLVanVsE9fb3rgWQNN7T0io8AvJEf3tMJhLROyG/k5LsWWaex2DE",
	"9MH08ayaHj04mjt9mI4eyh4pnPp2/PjpES19ZOrCgTzy9bG2mukR1NO5CGTwyAvOrF+F2wFxpkA0NoPk",
	"MxOip4936IfS/bp2bwGsUHIU9BUoJmgCpMTzZk7jXlhm95IEpFh37E1eciFllY3V6tLb8JR9wyUDKIii",
	"Y4YJqI4WrWbOEAJUIxlNYkXFBInIUHS4/t0APDkwdvTwgSPIm6j2QE+4kcaUjZrqTH94qdcKHi7pK4Yp",
	"i2VM3Vu0ZARXpeQgijz1eDtA0Q8ERgq4GAzydgCIKBUJ/eGBCUCViIb6oxTKkBmLmfFz/FMWJhU6idVj",
	"9egIGhUMkwlsEvNfBDPLv+e0i9gQmjEU+zOyC/S9AA1Fu1lgUeBu32xIu8+7ylxXoIPQaImLYH5dYbAH",
	"VMsZBSuCB+68FoGnJ7WcMW6hfz1PpB0yGvq55LN9uvWvX/vD15t97tT4xVC54a/cZCbwtxH02I7S1AfR",
	"DpyLaHqAJs2BSwoxQL6MjjYAKwDo5ToJoKgIeiHPNCuPhRZ6oUlzrjCFnqehU4h3/n//8nJt7RGQ5fpS",
	"5a/lcLJ8jdlIPj/GBX/aOHLGv3qhZCI5NCAlBxJ7xqRhWRqWU0OxxOCQlJD+lxiWE4kWMhuzGbgn+VeO",
	"CGKKYk/Fe2J79wxKwymf4qRfcbK34jYx0IpbENIY1mkvDvk212JzMlIIUWbCcJ9yC0GQ2Ga64qGHHZGJ",
	"s2NkaKCwDsHShgtBDysg3GgCFrPgit/EsX2zurRZW7v+/u3d7sM0Tz8E91OqfnNF4DCMXBe95yK7UdfD",
	"sJ1MyokheSgVG0qk9qaG/awaFH3uDHYBd4icPv0P7wuf0BC6bQz/HDG2ucf4jmc8sO4kRrPUx2fhI60W",
	"XZLkMQs4NaguXK1s/OyUbjv2glNaTe9vnCTVKVSZv/Zx5UE4efZzuXXydN1tgo6+mkCV6osNrMyttca1",
	"H7WTIqD3tg4JJjoYkwrbGD4LAFojhZt5QTWxuwjgaY2ynRwkPAF20xZUNQObfy8U1N7dap6FdEwAkPzR",
	"GZ6n7QMguYsASOxMydzdcWAnC2a/yCQ4AwMugDJrFgx1t0AZ3soL2wCle0odXprGeQK+tNK0jfGCw1jy",
	"v5+qLl2trC9Xb2/WXlz5WPrR+1qqAUTXf7U+kBRFlGwTMbdYubba5Umpn9dXfQ8y/XXPz00JHgpZyGu6",
	"xrAq6Mq0ICWEzKRCYrvEDhfOAf282Lw020Af3wxhdfGgERUnin8HAAD//8xeK2tAHQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
