// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code エラーコード。
	Code int `json:"code"`

	// Message エラーメッセージ。
	Message string `json:"message"`
}

// JwtError defines model for JwtError.
type JwtError struct {
	// Message ユーザ向けのメッセージ。
	Message string `json:"message"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Detail 特定の発生事象に関する詳細な説明。
	Detail *string `json:"detail,omitempty"`

	// Instance エラーが発生したリソースのURI。
	Instance *string `json:"instance,omitempty"`

	// RequestId デバッグ用のリクエストID。
	RequestId *string `json:"request_id,omitempty"`

	// Status 発生したHTTPステータスコード。
	Status int32 `json:"status"`

	// Title エラーの短い要約。
	Title string `json:"title"`

	// Type エラータイプを識別するURI。
	Type string `json:"type"`
}

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	// Title タスクのタイトル。
	Title string `json:"title"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CreatedAt タスクの登録日時。
	CreatedAt string `json:"created_at"`

	// Id タスクのID。
	Id uint64 `json:"id"`

	// Title タスクのタイトル。
	Title string `json:"title"`

	// UpdatedAt タスクの更新日時。
	UpdatedAt string `json:"updated_at"`
}

// UserRequest ユーザーアカウント情報。
type UserRequest struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Password ユーザーの平文のパスワード。
	Password string `json:"password"`
}

// UserResponse ユーザーアカウント情報。
type UserResponse struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Id ユーザーの固有識別子。
	Id uint64 `json:"id"`
}

// JWT defines model for JWTトークンエラー.
type JWT = JwtError

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XCSRFTOKEN CSRFトークン。
	XCSRFTOKEN *string `json:"X-CSRF-TOKEN,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = UserRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = TaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context, params LoginParams) error
	// ログアウト
	// (POST /logout)
	Logout(ctx echo.Context) error
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx echo.Context) error
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx echo.Context) error
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx echo.Context) error
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx echo.Context, taskId int) error
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx echo.Context, taskId int) error
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx echo.Context, taskId int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Csrf converts echo context to params.
func (w *ServerInterfaceWrapper) Csrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Csrf(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-TOKEN")]; found {
		var XCSRFTOKEN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-TOKEN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-TOKEN", valueList[0], &XCSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-TOKEN: %s", err))
		}

		params.XCSRFTOKEN = &XCSRFTOKEN
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx, params)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// GetAllTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllTasks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllTasks(ctx)
	return err
}

// CreateTask converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTask(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTask(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, taskId)
	return err
}

// GetTaskById converts echo context to params.
func (w *ServerInterfaceWrapper) GetTaskById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTaskById(ctx, taskId)
	return err
}

// UpdateTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTask(ctx, taskId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.Csrf)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.POST(baseURL+"/signup", wrapper.SignUp)
	router.GET(baseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(baseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(baseURL+"/tasks/:taskId", wrapper.DeleteTask)
	router.GET(baseURL+"/tasks/:taskId", wrapper.GetTaskById)
	router.PUT(baseURL+"/tasks/:taskId", wrapper.UpdateTask)

}

type JWTJSONResponse JwtError

type CsrfRequestObject struct {
}

type CsrfResponseObject interface {
	VisitCsrfResponse(w http.ResponseWriter) error
}

type Csrf200JSONResponse struct {
	// CsrfToken CSRFトークン。
	CsrfToken string `json:"csrf_token"`
}

func (response Csrf200JSONResponse) VisitCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200Response struct {
	Headers Login200ResponseHeaders
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type Login400JSONResponse string

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse ErrorResponse

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200ResponseHeaders struct {
	SetCookie string
}

type Logout200Response struct {
	Headers Logout200ResponseHeaders
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201JSONResponse UserResponse

func (response SignUp201JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SignUp409ApplicationProblemPlusJSONResponse ProblemDetails

func (response SignUp409ApplicationProblemPlusJSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SignUp500ApplicationProblemPlusJSONResponse ProblemDetails

func (response SignUp500ApplicationProblemPlusJSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasksRequestObject struct {
}

type GetAllTasksResponseObject interface {
	VisitGetAllTasksResponse(w http.ResponseWriter) error
}

type GetAllTasks200JSONResponse []TaskResponse

func (response GetAllTasks200JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks401JSONResponse struct{ JWTJSONResponse }

func (response GetAllTasks401JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks500JSONResponse string

func (response GetAllTasks500JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse TaskResponse

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask400JSONResponse map[string]interface{}

func (response CreateTask400JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask401JSONResponse struct{ JWTJSONResponse }

func (response CreateTask401JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask500JSONResponse map[string]interface{}

func (response CreateTask500JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	TaskId int `json:"taskId"`
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTask401JSONResponse struct{ JWTJSONResponse }

func (response DeleteTask401JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask500JSONResponse string

func (response DeleteTask500JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByIdRequestObject struct {
	TaskId int `json:"taskId"`
}

type GetTaskByIdResponseObject interface {
	VisitGetTaskByIdResponse(w http.ResponseWriter) error
}

type GetTaskById200JSONResponse TaskResponse

func (response GetTaskById200JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskById500JSONResponse string

func (response GetTaskById500JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	TaskId int `json:"taskId"`
	Body   *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse TaskResponse

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask500JSONResponse string

func (response UpdateTask500JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx context.Context, request CsrfRequestObject) (CsrfResponseObject, error)
	// ログイン
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウト
	// (POST /logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx context.Context, request GetAllTasksRequestObject) (GetAllTasksResponseObject, error)
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx context.Context, request GetTaskByIdRequestObject) (GetTaskByIdResponseObject, error)
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Csrf operation middleware
func (sh *strictHandler) Csrf(ctx echo.Context) error {
	var request CsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Csrf(ctx.Request().Context(), request.(CsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Csrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CsrfResponseObject); ok {
		return validResponse.VisitCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context, params LoginParams) error {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllTasks operation middleware
func (sh *strictHandler) GetAllTasks(ctx echo.Context) error {
	var request GetAllTasksRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTasks(ctx.Request().Context(), request.(GetAllTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllTasksResponseObject); ok {
		return validResponse.VisitGetAllTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(ctx echo.Context) error {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx.Request().Context(), request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		return validResponse.VisitCreateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(ctx echo.Context, taskId int) error {
	var request DeleteTaskRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx.Request().Context(), request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		return validResponse.VisitDeleteTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTaskById operation middleware
func (sh *strictHandler) GetTaskById(ctx echo.Context, taskId int) error {
	var request GetTaskByIdRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskById(ctx.Request().Context(), request.(GetTaskByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTaskByIdResponseObject); ok {
		return validResponse.VisitGetTaskByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(ctx echo.Context, taskId int) error {
	var request UpdateTaskRequestObject

	request.TaskId = taskId

	var body UpdateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx.Request().Context(), request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		return validResponse.VisitUpdateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaaXMTRxr+K1O9+y2SdVhe8FBULebYiGyBg+3NpigXNda05QHNQXcrWKFUxcwkwWBv",
	"YrzExgtVDi5ijB0fWVPZcIUf00gW/2Kre3TMSDOjkWNns3ywxRxvv8fzvP28bd0EOV01dA1qBAPxJkAQ",
	"G7qGIf/P+U9GqT1D7dfU2qH2HrXWqf2M2q/ZvZyuEagR9lEyjIKSk4iia4mrWNfYNTgtqUahuxlcVFUJ",
	"lYAY/FQMfCYVipA9rUKMpTwEIlAVjBUtL+hIUKXCpI5UKAtXbxBQLpdjAOemoCqxN/6I4CQQwR8SrTAT",
	"zl2cOH+DnEVIR847MsQ5pBgsCseb2sY/auuvqbnddIXeskDLPI+NG7hUTxq7YCDdgIgoTug5XeZXvcZb",
	"Bq099tO+wyzHACkZLDZFIzAPESjHWgEHm7AfU9um1itu7mePIUyQouW5ywheLyoIykC87DjVsj3efF6f",
	"uApzhK3bTE1HRMEe2WvchZ8q8/eoeY/lrXfXwnwaRvpEAapnIJGUAu70TOY3Oh3bv/Oisv0vam7vL7/c",
	"v7/y7uVs7cfH1Nx8v7hKzWVqzdae7e0/36XmRm3jh+qDrx0/6wAGIqjO3ebvf0utOWquZM9Qa6E6Z1Lz",
	"CbVWqfWE2l9R+ztq7lS2HlQerVNziZq/UPMhtf7pG3IMKBomkpYLLas557jLza1Qe4Nab3geX1Bze+xS",
	"tt3LRBFDhBOpdH9mAMQAY4REgAiKSPFzgSUdYnJFkf0qeZva87x0u/v313klNxgrrXW2vD2TPdO+OoLX",
	"49Olz+OpdL/faphIpIh9SuMK8cPR0WFu/ise5lv22UuP5nKZZMYVoaKR/rQve4hCCuFJ3t5f2aLmF7U1",
	"c//5F+1BeZM+V1ubZTU3Z6l1t1lhv2idCyGkf8tRs0SthdrWg8rM9w4MfYo6RYiBxUSifqUvp6sJA+kT",
	"OKHpJD6pFzW5a63bGMbvNlLTrIwf30YlfO2SA5NOsgWm1qnbDm+bTpwz1N6Mwn3HZLAngT0WQYlA+YpE",
	"wv3ZX371fu7f1aXvq8tWEDHlcBMN4LcyrmjkT5newNdDhmKgaMiRgqs+fF5d3A0Jri3ZiuwCgSuDnhX9",
	"ajGGIXKhImAP4D9XqbVJrTW2mdszVfvLync/Oq556wdV37btsVXfTF6zRFmrrCPYP7DY/ZNmSBjf0JHc",
	"1WjlxV518Ta3fo/3nh2f7Tggg47brsWCs9VC7u8yXUqERD18WX10x+lWla35qCzwA53jf2eyynxjnNQb",
	"4lLKMYB1CLNRXdZ5TEusPZvbbHO0TGpunxrOUvMpa6VOlA79+PPCqeEsk5EQYcdIqi/JAtcNqEmGAkTQ",
	"35fsS/Fikime5UQOo0n2IQ99cH565NI5r1hd2L+/Up2Zdzq54wErGhfFWZm9wuzFvPo6nUxGl9L8SYwm",
	"rxD9GmROTJ/LfjwpZ4fODeU//QgPnZ+8UPzkb2Mff3pKyV64ev1sAXiEcFvPdBnqGlwUSdmy519Z7xKO",
	"ioa5IlJICYiXx2OuQaBjfa7cao/nmBdSHrP1mNgB48xKoqDnFR6FoYe3JEaKLWrt8pbLSlbZXqkuvgku",
	"2V+5ZQYKJKmQQMSWjpat1hYOGKrZVg4lGSIQA5qksut/j7M346MXPzp7AbgL1Z7o8aZYG9LlUm94qfcK",
	"nq7UnwnEhEkId9MSAbvKZFvkscm9A5S9QCCoCMv+IG8DQKyeEP7ICCTx07p+TfHdL19xJfofaj+l9h5X",
	"35X5TWrdYoJRcF6j9gP2kH2rPqS5C8BReVKayKXS/dOlz48dHzwhDEtk6mTihPAhIcZFrVA6IYwwMMIT",
	"woikwhGFwJMjBCk5EloZFnsmEoVDbHRSIwYGeu4LfMwcSCZdEyPIoZJB9MQE/y0KUxKegvJwvfCCggVN",
	"JwKZgvyOoE/yz3nlM6gJTXhEBoV3Du6V8m5iBrJcL5IoNLcWGtZW+W46E0pwZvSwAbvDAbtVn+KevaTm",
	"JjU3qDXbBU0RElQPyT9HWMlrRSNCjhwlHKEDjih5bcwA//cdKHVITjOllPL4Pt3616v/wVw57ehxwPvL",
	"YIjvhnMk8kHUlgAZSwUu9xUtL7D4RKEtyshRtJ3HHKiX9RpAI/Nis0WxRtYof9/hOh/KRw+VOvgYA9Nx",
	"nNbjNySkMXqL4GKDWAIjp1gnK+u9glosEMUoQKHFMibTOKeJhK/hQB3qngDf/XyrtvaUkfqbxcovS8Gk",
	"/gskpwqFUW741wnSy97hG6ST6YF4Kh1PHhtNDYqpQTEz0JfsH0glUx8kB8VkssWghjpn4aW8Q2cEM+VY",
	"14WP9R0/1p8azHgWTnsXTndfuM0ME2MtfCkEqrgb0DxnF83DISAhJJWCOJNxGpaf2Wa5EoHn5ZEFRE+q",
	"JIwMDRTWIWhuOxB0sYKlG4yz0dx/Z2ri2FqoLu7W1r559+ZR+DjFy8+S+2t2p+aQyGEYuXm4T8aOYv8J",
	"wnY6LSYHxIFM30Ayczwz6GVVf8wTTn8IuAPs9Bh/mNY7sDAOmxn/d8Q44CTrOaBzwbqTGM1Wn7jJfmXl",
	"skOSAiQ+ErPzLxL1s8Q6hSp37r5ffhJMnjPcbp08odOt3+FnE6ip+mhrSGSqNdg6/oN2UvhI39Yx0XgH",
	"YzI+Evy3A0BrenQqL8g6dOYlOK3gLlPhgSHilM2va/pu/t1QUHt7v3ka1qEAWPGHSrxOBwdA+ggBkDyc",
	"lnm0cuAwG2avyEQwx+QvA2XjD0FHAsrgrbx4AFA6f6cIbk1jvAC/t9Z0AHnBYZzyfsWhuni7srVU/Xa3",
	"9tOX782v3d9saADRiV+uC5JyDKTbTMzMV+6uhLyZ6uUbED0Lmd52z9+aEjwVolBQVIVAWVClaSGVFHJT",
	"Euo7InY4cPbZz8vNSzcb6OOTIRtdXGgE5fHyfwMAAP//Etmg6IMjAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
