// Code generated by MockGen. DO NOT EDIT.
// Source: task_usecase.go
//
// Generated by this command:
//
//	mockgen -source=task_usecase.go -destination=../../mock/usecase/mock/mock_task_usecase.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	reflect "reflect"
	entity "rest-api-codegen/internal/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockITaskUsecase is a mock of ITaskUsecase interface.
type MockITaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockITaskUsecaseMockRecorder
	isgomock struct{}
}

// MockITaskUsecaseMockRecorder is the mock recorder for MockITaskUsecase.
type MockITaskUsecaseMockRecorder struct {
	mock *MockITaskUsecase
}

// NewMockITaskUsecase creates a new mock instance.
func NewMockITaskUsecase(ctrl *gomock.Controller) *MockITaskUsecase {
	mock := &MockITaskUsecase{ctrl: ctrl}
	mock.recorder = &MockITaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskUsecase) EXPECT() *MockITaskUsecaseMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockITaskUsecase) CreateTask(task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockITaskUsecaseMockRecorder) CreateTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockITaskUsecase)(nil).CreateTask), task)
}

// DeleteTask mocks base method.
func (m *MockITaskUsecase) DeleteTask(userID, taskID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockITaskUsecaseMockRecorder) DeleteTask(userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockITaskUsecase)(nil).DeleteTask), userID, taskID)
}

// GetAllTasks mocks base method.
func (m *MockITaskUsecase) GetAllTasks(userID uint64) ([]*entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", userID)
	ret0, _ := ret[0].([]*entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockITaskUsecaseMockRecorder) GetAllTasks(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockITaskUsecase)(nil).GetAllTasks), userID)
}

// GetTaskByID mocks base method.
func (m *MockITaskUsecase) GetTaskByID(userID, taskID uint64) (*entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", userID, taskID)
	ret0, _ := ret[0].(*entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockITaskUsecaseMockRecorder) GetTaskByID(userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockITaskUsecase)(nil).GetTaskByID), userID, taskID)
}

// UpdateTask mocks base method.
func (m *MockITaskUsecase) UpdateTask(task *entity.Task, userID, taskID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", task, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockITaskUsecaseMockRecorder) UpdateTask(task, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockITaskUsecase)(nil).UpdateTask), task, userID, taskID)
}
