// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	// Message ユーザ向けのメッセージ。
	Message string `json:"message"`
}

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	// Title タスクのタイトル。
	Title string `json:"title"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CreatedAt タスクの登録日時。
	CreatedAt string `json:"created_at"`

	// Id タスクのID。
	Id uint64 `json:"id"`

	// Title タスクのタイトル。
	Title string `json:"title"`

	// UpdatedAt タスクの更新日時。
	UpdatedAt string `json:"updated_at"`
}

// UserRequest ユーザーアカウント情報。
type UserRequest struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Password ユーザーの平文のパスワード。
	Password string `json:"password"`
}

// UserResponse ユーザーアカウント情報。
type UserResponse struct {
	// Email ユーザーのメールアドレス。
	Email string `json:"email"`

	// Id ユーザーの固有識別子。
	Id uint64 `json:"id"`
}

// JWT defines model for JWTトークンエラー.
type JWT = ApiResponse

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XCSRFTOKEN CSRFトークン。
	XCSRFTOKEN *string `json:"X-CSRF-TOKEN,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = UserRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = TaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context, params LoginParams) error
	// ログアウト
	// (POST /logout)
	Logout(ctx echo.Context) error
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx echo.Context) error
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx echo.Context) error
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx echo.Context) error
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx echo.Context, taskId int) error
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx echo.Context, taskId int) error
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx echo.Context, taskId int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Csrf converts echo context to params.
func (w *ServerInterfaceWrapper) Csrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Csrf(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-CSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-TOKEN")]; found {
		var XCSRFTOKEN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-TOKEN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-TOKEN", valueList[0], &XCSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-TOKEN: %s", err))
		}

		params.XCSRFTOKEN = &XCSRFTOKEN
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx, params)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// GetAllTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllTasks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllTasks(ctx)
	return err
}

// CreateTask converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTask(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTask(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, taskId)
	return err
}

// GetTaskById converts echo context to params.
func (w *ServerInterfaceWrapper) GetTaskById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTaskById(ctx, taskId)
	return err
}

// UpdateTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "taskId" -------------
	var taskId int

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", ctx.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter taskId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTask(ctx, taskId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.Csrf)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.POST(baseURL+"/signup", wrapper.SignUp)
	router.GET(baseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(baseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(baseURL+"/tasks/:taskId", wrapper.DeleteTask)
	router.GET(baseURL+"/tasks/:taskId", wrapper.GetTaskById)
	router.PUT(baseURL+"/tasks/:taskId", wrapper.UpdateTask)

}

type JWTJSONResponse ApiResponse

type CsrfRequestObject struct {
}

type CsrfResponseObject interface {
	VisitCsrfResponse(w http.ResponseWriter) error
}

type Csrf200JSONResponse struct {
	// CsrfToken CSRFトークン。
	CsrfToken string `json:"csrf_token"`
}

func (response Csrf200JSONResponse) VisitCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200Response struct {
}

func (response Login200Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Login400JSONResponse string

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse string

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201AsteriskResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response SignUp201AsteriskResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(201)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type SignUp400JSONResponse string

func (response SignUp400JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SignUp500JSONResponse string

func (response SignUp500JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasksRequestObject struct {
}

type GetAllTasksResponseObject interface {
	VisitGetAllTasksResponse(w http.ResponseWriter) error
}

type GetAllTasks200JSONResponse []TaskResponse

func (response GetAllTasks200JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks401JSONResponse struct{ JWTJSONResponse }

func (response GetAllTasks401JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTasks500JSONResponse string

func (response GetAllTasks500JSONResponse) VisitGetAllTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse TaskResponse

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask400JSONResponse map[string]interface{}

func (response CreateTask400JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask401JSONResponse struct{ JWTJSONResponse }

func (response CreateTask401JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask500JSONResponse map[string]interface{}

func (response CreateTask500JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	TaskId int `json:"taskId"`
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTask401JSONResponse struct{ JWTJSONResponse }

func (response DeleteTask401JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask500JSONResponse string

func (response DeleteTask500JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByIdRequestObject struct {
	TaskId int `json:"taskId"`
}

type GetTaskByIdResponseObject interface {
	VisitGetTaskByIdResponse(w http.ResponseWriter) error
}

type GetTaskById200JSONResponse TaskResponse

func (response GetTaskById200JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskById500JSONResponse string

func (response GetTaskById500JSONResponse) VisitGetTaskByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	TaskId int `json:"taskId"`
	Body   *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse TaskResponse

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask500JSONResponse string

func (response UpdateTask500JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CSRFトークンの発行
	// (GET /csrf)
	Csrf(ctx context.Context, request CsrfRequestObject) (CsrfResponseObject, error)
	// ログイン
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウト
	// (POST /logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ユーザ登録
	// (POST /signup)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// タスク一覧の取得
	// (GET /tasks)
	GetAllTasks(ctx context.Context, request GetAllTasksRequestObject) (GetAllTasksResponseObject, error)
	// タスクの新規作成
	// (POST /tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// タスクの削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)
	// タスクの取得
	// (GET /tasks/{taskId})
	GetTaskById(ctx context.Context, request GetTaskByIdRequestObject) (GetTaskByIdResponseObject, error)
	// タスクの更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Csrf operation middleware
func (sh *strictHandler) Csrf(ctx echo.Context) error {
	var request CsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Csrf(ctx.Request().Context(), request.(CsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Csrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CsrfResponseObject); ok {
		return validResponse.VisitCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context, params LoginParams) error {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAllTasks operation middleware
func (sh *strictHandler) GetAllTasks(ctx echo.Context) error {
	var request GetAllTasksRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTasks(ctx.Request().Context(), request.(GetAllTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllTasksResponseObject); ok {
		return validResponse.VisitGetAllTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(ctx echo.Context) error {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx.Request().Context(), request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		return validResponse.VisitCreateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(ctx echo.Context, taskId int) error {
	var request DeleteTaskRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx.Request().Context(), request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		return validResponse.VisitDeleteTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTaskById operation middleware
func (sh *strictHandler) GetTaskById(ctx echo.Context, taskId int) error {
	var request GetTaskByIdRequestObject

	request.TaskId = taskId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskById(ctx.Request().Context(), request.(GetTaskByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTaskByIdResponseObject); ok {
		return validResponse.VisitGetTaskByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(ctx echo.Context, taskId int) error {
	var request UpdateTaskRequestObject

	request.TaskId = taskId

	var body UpdateTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx.Request().Context(), request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		return validResponse.VisitUpdateTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZa2/TVhj+K9bZPjE3idN0UH9ay2UKTFzbMYQqZOKTxCW+4HMCrapIxBaiZd0oCNp1",
	"IHUgKAzW0o0JcSnjx5iE8C+m9zgXO7ETp7SM8YGkjv1en+e9HM+gjK4auoY1SpA4g0xMDF0jmP1x8OSY",
	"Y8869qZjPXXsZ471yLF/d+xN+C2jaxRrFL5KhlFQMhJVdC0+SXQNruEpSTUKvcWQoqpK5jQSw+/i0QWp",
	"UMRwt4oJkXIYiUhVCFG0HKebnCoVsrqpYpmbvEhRqVTiEcnksSrBE1+aOItE9EW85Wbc/ZXERwzleN1d",
	"9zEZk4ypGOCIa1Dt8U+1R5tOeb1pjXPJQi0NzD2vGHEGGaZuYJMqru9Ni2fapDv2KvP1eWXhulO+Djrs",
	"u45tO9Zrdv0FaOIRnTbAXUJNRcsxzSY+X1RMLCPxdFP6RPNG/ewkzlBU4tGYRM4dx+eLmNBOs6hCC0FG",
	"WW8d6yUkAFx+61j3WUqeRLHFFRluSViEMiaWKJbPSLS7Pe+XX3+Y/6u69KC6bAXawyNF7i4ivc99EOAC",
	"6lBR0ejXqZYoRaM4h02QtR0R4lHRkCM5V739d3Vxo4tzbcFWZNQwkfdG0KcxKBfjBJseVIRgkv1/z7Ge",
	"ONYqcNGerdqXK7/96Zrmzx9WJaXQQ1Yd3JsQKOueY8859h/ge3DQDImQi7op9xRaefmsuniFSb8O4uyn",
	"TMdclAi6ZnuUhUerhdzPMlxKhEDdflW9M1db+6Uy+6CythCVBUGgc+3vDBbcrGhZvdEbpAwArKOojumy",
	"znxacuzH4Gh5xbHKTnl95GjaKT90yst1L136of2ZvM7BQ9zI0TS0AmwSV5IQS4D3uoE1yVCQiAZjiZjA",
	"MkrzLNTxDDGz8CWHA8C+98TxA/6Gc+P9zZXq7ALYYP3omgGZY40tLcMjII/398hkIhG9HbI7iZk9Q/Vz",
	"GIyYOpA+lpXTowdGc6cOkdGD2cPFk9+PHzs1oqQPT57fX0C+ZtZWOD2CejoXgREeecHp9atw2yDOFE2F",
	"TiPx9ATvaeYd+qF+v6rdnQcrpBwBfUWCTTQBUuIFPacwLwy9e10CZqw51garu5CyyvpKdfFNeMq+Y5IB",
	"FKakYopNUB0tWs2cIQTQRiLKY0nGJuKRJqlw/YcBeHJg7Mih/YeRN1HtgZ5wI40JHdXl6f7wUi8YLFzC",
	"NxQTGsvoqrdyiQiuCslBFHn08baBkh8I1CziUjDI2wHAo1Qk9IcHJgBVPBrqj1IoY04bVI+fZZ8il5dI",
	"HstH69HhFMJpOuVoHrNfOD3LvueUC1jjmjHk+zOyC/S9AA1Fu16kUeBu3WhIu8day2xXoIPQaImLYH5d",
	"YbAHRMlpRSOCB+7QFoGnJ5ScNm6g/z1PhDajd8V3RbUT+rjgM3eq9a9fk8PXmr3utPjZsLfhr9gkI1C2",
	"EefYtjLTh8oOaPNoaoAk9YGLkqmBfBEdaWCUA5yLddxDHeHUYoEqRgFzLcBCX2b0oBI5R0IHD+/c/+7F",
	"pdrqQ+DHtcXKP0vh/PgW05FCYYwJ/rgJ5LR/5ULJRHJoQEgOJHaPCcOiMCymhmKJwSEhIXyVGBYTiRYy",
	"GzMZuCf4V40IYkp8T8W7Y3t2DwrDKZ/ipF9xsrfiNjHQfVsQUihWSS8O+TbWUnMYkkxTmg7DfcrlfpDY",
	"ZrrioYcckYmzbWRooLAOwfK6C0EPKyDcaAIWsuAi38SxdaO6uFFbvfbuzZ3u8zNLPwT3Ywp9Aw1jDIaR",
	"66L3PGRLpbzXXB+C7WRSTAyJQ6nYUCK1JzXsZ9Ug73NnsAu4Q+T06X94X/iIhtBtSfjviLHF1cV3LOOB",
	"dScxmqU+PgMfabnkkqSAacBpQXX+SmX9V6d8y7HmnfJKel/jBKlOocrc1Q/L98PJs4/JrZOn6zoTdOTV",
	"BKpQ32VgS25tMq79qJ0UAb23dTgw0cGYVNiS8EkA0Bop3Mxzso7d2R9PKYRu5yDhCbCbtqCqGdj8e6Gg",
	"9vZm8wykYwKA5I9OszxtHQDJHQRAYntK5s6OA9tZMPtFpokzMOACKLN6UZN3CpThrby4BVC6p9PhpWmc",
	"JeBzK01bGC8YjAX/e6nq4pXK2lL11kbt+eUP5Z+9r6MaQHT9l+sDSYlHyTYRswuVqytdnhT6eW3V9yDT",
	"X/f81JRgoRC5gqIqFMucKk1xQoLL5CUztkPscOEc0M9LzUszDfSxzRBWFw8aUWmi9G8AAAD//8xoh0c4",
	"HQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
